# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JSPspEmu
email: soywiz@gmail.com
excerpt_separator: <!--more-->
description: Technical information and releases about a psp emulator made in javascript
baseurl: ""
url: "http://blog.jspspemu.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
